### ISSUE TITLE
请问这个骨架还有维护吗

### ISSUE THREAD

**Issue by kjddz** [limingxinleo/tenant-skeleton#1]
请问这个骨架还有维护吗？我想使用，但是这个好像用的是hyperf v1.1，我目前用的是v2.2，另外composer.json里面的init-proxy.sh是否为必需的呢？

**Comment by limingxinleo** [comment]
不维护，你可以参考一下代码，不要直接使用了。

**Comment by limingxinleo** [comment]
算了，我更新一下吧

**Comment by limingxinleo** [comment]
好了，已经升级到最新版了

**Comment by kjddz** [comment]
谢谢大哥

**Comment by kingIZZZY** [comment]
Hello, asking similar updated status now in July 2023
Can you please either:
- Refer which specific parts of the code should I study and copy for my codebase (my project is latest composer created skeleton project)
- Or... maybe this can be updated again please 🙏

**Comment by limingxinleo** [comment]
> Hello, asking similar updated status now in July 2023 Can you please either:
> 
> * Refer which specific parts of the code should I study and copy for my codebase (my project is latest composer created skeleton project)
> * Or... maybe this can be updated again please 🙏

@kingIZZZY You can get the changed code by the url below

https://github.com/limingxinleo/tenant-skeleton/compare/parent...master
